<?php
// $Id$

/**
 * @file
 * Module for the entity API.
 */

spl_autoload_register('entity_autoload');

/**
 * Autoload API includes. Note that the code registry autoload is used only
 * by the providing API module.
 */
function entity_autoload($class) {
  if (stripos($class, 'faces') === 0) {
    module_load_include('inc', 'entity', 'faces');
  }
}

/**
 * Defines status codes used for exportable entities.
 */

/**
 * A bit flag used to let us know if an entity is in the database.
 */
define('ENTITY_IN_DB', 0x01);

/**
 * A bit flag used to let us know if an entity is a 'default' in code.
 */
define('ENTITY_IN_CODE', 0x02);

/**
 * A bit flag used to mark entities as fixed, thus not changeable for any
 * user.
 */
define('ENTITY_FIXED', 0x04);

