<?php
// $Id$

/**
 * @file
 * Test moduel for the entity API.
 */

/**
 * Implement hook_entity_info().
 */
function entity_test_entity_info() {
  $return = array(
    'entity_test' => array(
      'label' => t('Test Entity'),
      'entity class' => 'EntityClass',
      'controller class' => 'EntityAPIController',
      'base table' => 'entity_test',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'pid',
        'bundle' => 'name',
      ),
      'bundles' => array(),
      'bundle keys' => array(
        'bundle' => 'name',
      ),
    ),
  );
  $return['entity_test_type'] = array(
    'label' => t('Test entity type'),
    'entity class' => 'EntityDB',
    'controller class' => 'EntityAPIController',
    'base table' => 'entity_test_type',
    'fieldable' => FALSE,
    'bundle of' => 'entity_test',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'name',
    ),
  );
  return $return;
}

/**
 * Implement hook_entity_info_alter().
 *
 * Use this hook to specify entity test bundles to avoid a recursion, as loading
 * the entity test types needs the entity info too.
 */
function entity_test_entity_info_alter(&$entity_info) {
  foreach (entity_test_get_types() as $name => $info) {
    $entity_info['entity_test']['bundles'][$name] = array(
      'label' => $info->label,
    );
  }
}

/**
 * Gets an array of all test entity types, keyed by the name.
 *
 * @param $name
 *   If set, the type with the given name is returned.
 */
function entity_test_get_types($name = NULL) {
  $types = entity_load('entity_test_type', isset($name) ? array($name) : FALSE);
  if (isset($name)) {
    return isset($types[$name]) ? $types[$name] : FALSE;
  }
  return $types;
}

/**
 * Load multiple test entities based on certain conditions.
 *
 * @param $pids
 *   An array of entity IDs.
 * @param $conditions
 *   An array of conditions to match against the {entity} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of test entity objects, indexed by pid.
 */
function entity_test_load_multiple($pids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('entity_test', $pids, $conditions, $reset);
}

/**
 * Delete multiple test entities.
 *
 * @param $pids
 *   An array of test entity IDs.
 */
function entity_test_delete_multiple(array $pids) {
  entity_get_controller('entity_test')->delete($pids);
}

/**
 * Implement hook_entity_test_type_presave().
 */
function entity_test_entity_test_type_presave($type) {
  $data = get_object_vars($type);
  unset($data['name'], $data['label'], $data['weight'], $data['locked'], $data['data'], $data['status']);
  $type->data = $data;
}


/**
 * Implement hook_default_entity_test_type().
 */
function entity_test_default_entity_test_type() {
  $types['main'] = new EntityDB(array(
      'name' => 'main',
      'label' => t('Main test type'),
      'weight' => 0,
      'locked' => TRUE,
  ), 'entity_test_type');

  // Types used during CRUD testing.
  $types['test'] = new EntityDB(array(
    'name' => 'test',
    'label' => 'label',
    'weight' => 0,
  ), 'entity_test_type');
  $types['test2'] = new EntityDB(array(
      'name' => 'test2',
      'label' => 'label2',
      'weight' => 2,
  ), 'entity_test_type');

  return $types;
}

/**
 * Main class for test entities.
 */
class EntityClass extends EntityDBExtendable {

  public function __construct(array $values = array(), $entityType = NULL) {
    parent::__construct($values, 'entity_test');
  }

}
